# Generated by Django 2.1 on 2018-08-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.SlugField()),
                ('last_run_timestamp', models.DateTimeField(null=True)),
                ('call_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockFacetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.SlugField()),
                ('value', models.CharField(db_index=True, max_length=200)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.SlugField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='stockfacetrecord',
            name='stock_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockandflow.StockRecord'),
        ),
    ]
